# Generated by Django 2.2.2 on 2019-06-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
