# Generated by Django 2.2.2 on 2019-06-07 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0004_fanart_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fanarts', to='pokemon_app.User'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='pokemon_app.User'),
        ),
    ]
