# Generated by Django 2.2.2 on 2019-06-07 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0005_auto_20190607_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanart',
            name='create_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
