# Generated by Django 2.2.2 on 2019-06-12 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0006_fanart_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanart',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
