# Generated by Django 2.2.2 on 2019-06-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0007_auto_20190612_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanart',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
