# Generated by Django 2.2.2 on 2019-06-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0008_auto_20190612_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanart',
            name='file',
            field=models.FileField(default='https://assets.pokemon.com/assets/cms2/img/pokedex/full/025.png', upload_to=''),
        ),
    ]
