# Generated by Django 2.2.2 on 2019-06-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0009_fanart_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanart',
            name='file',
            field=models.ImageField(default='https://assets.pokemon.com/assets/cms2/img/pokedex/full/025.png', upload_to=''),
        ),
    ]
